# Generated by Django 5.2.6 on 2025-09-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tradeshow_show',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('x', models.IntegerField(default=20)),
                ('y', models.IntegerField(default=20)),
                ('width', models.IntegerField(default=140)),
                ('height', models.IntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('tradeshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='tradeshow.tradeshow')),
            ],
            options={
                'db_table': 'tradeshow_booth',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitors', to='tradeshow.booth')),
                ('tradeshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='tradeshow.tradeshow')),
            ],
            options={
                'db_table': 'tradeshow_exhibitor',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['tradeshow', 'company'], name='tradeshow_e_tradesh_e0d133_idx'), models.Index(fields=['booth'], name='tradeshow_e_booth_i_130dc2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='booth',
            constraint=models.UniqueConstraint(fields=('tradeshow', 'label'), name='uniq_booth_per_show'),
        ),
    ]
