# Generated by Django 4.2.23 on 2025-09-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('circular', 'Circular'), ('square', 'Square'), ('row', 'Row')], default='circular', max_length=10)),
                ('seat_count', models.PositiveSmallIntegerField(default=6)),
                ('x', models.IntegerField(default=40)),
                ('y', models.IntegerField(default=40)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='conference.meeting')),
            ],
            options={
                'unique_together': {('meeting', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='conference.attendee')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='conference.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='conference.meeting'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='assigned', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='conference.attendee')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='conference.table')),
            ],
            options={
                'unique_together': {('table', 'seat_index')},
            },
        ),
    ]
