# Generated by Django 4.2.23 on 2025-09-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='table',
            name='seat_count',
        ),
        migrations.RemoveField(
            model_name='table',
            name='type',
        ),
        migrations.AddField(
            model_name='assignment',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='conference.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('C', 'circle'), ('S', 'square'), ('R', 'row')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='seat_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='assigned', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='department',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='position',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='x',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='y',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
    ]
